### ISSUE TITLE
High resolution output?

### ISSUE THREAD

**Issue by cablecutter** [ProGamerGov/neural-style-pt#3]
Hey!  Glad to see you're still working on neural-style.  Very much intrigued by the PyTorch implementation, so I dropped a copy on my windows box to play around with.  

I was curious if you've continued to experiment with scaling and producing high resolution output and how you may have gone about achieving that with the PyTorch implementation.  Any differences to report?  Any changes in the GPU memory ceilings / resolution limits?  Any new scaling scripts to share?

**Comment by ProGamerGov** [comment]
> I was curious if you've continued to experiment with scaling and producing high resolution output and how you may have gone about achieving that with the PyTorch implementation. Any differences to report? 

The same multiscale resolution technique from Neural-Style, works with Neural-Style-PT as well. 

> Any changes in the GPU memory ceilings / resolution limits? Any new scaling scripts to share?

My code is significantly faster and more memory efficient than Justin Johnson's code.

**Comment by ProGamerGov** [comment]
> I was curious if you've continued to experiment with scaling and producing high resolution output and how you may have gone about achieving that with the PyTorch implementation. Any differences to report? 

The same multiscale resolution technique from Neural-Style, works with Neural-Style-PT as well. I haven't noticed any difference in the effectiveness of the technique with Neural-Style-PT.

> Any changes in the GPU memory ceilings / resolution limits? Any new scaling scripts to share?

My code is already faster and more memory efficient than Justin Johnson's code, so large image sizes are possible. PyTorch is also under active development, and as such its performance is likely to be improved.

**Comment by spot92** [comment]
I may need to mess with some settings then as I have been unable to do an image size larger than 1440 wide (per the image_size option) on a 1080 ti. I am absolutely loving this repo, but I am able to do larger images with other repos.

**Comment by ProGamerGov** [comment]
@spot92 What style transfer projects are you referring to?
