### ISSUE TITLE
vgg model does not calculate the style and content loss

### ISSUE THREAD

**Issue by eric11eca** [ProGamerGov/neural-style-pt#4]
When I use the vgg model, it does not calculate the content and style loss. It only prints out the total loss. The NIN model works just fine.

**Comment by ProGamerGov** [comment]
Can you please elaborate on this issues your having? What PyTorch version you are using? What are the outputs for the content/style loss? Is the output still stylized?

**Comment by ProGamerGov** [comment]
If this issue still exists, then please reopen the issue.
