### ISSUE TITLE
Tiling

### ISSUE THREAD

**Issue by spot92** [ProGamerGov/neural-style-pt#51]
How hard would it be to get tiling? I have been working on doing this, but I am struggling to figure out how to style the tiles that I have from a large image. Trying not to do it one at a time, but some sort of for loop situation.

**Comment by ProGamerGov** [comment]
There's two options. 

1. You could translate VaKonS' neural-style which has tiling built into it: https://github.com/VaKonS/neural-style. This is probably going to be the hardest option.

2. Or you could use a bash script from here: https://github.com/ProGamerGov/Neural-Tile/ and just paste in your neural-style-pt parameters. This will be the easiest option if you want some automation.

**Comment by spot92** [comment]
I'll look into these, thanks!

**Comment by spot92** [comment]
If a batch file version of the https://github.com/ProGamerGov/Neural-Tile/ is ever made by someone to work with the python code, I would be interested in it. Working on figuring it out myself.
