### ISSUE TITLE
NIN Upres

### ISSUE THREAD

**Issue by spot92** [ProGamerGov/neural-style-pt#52]
Looking at the post here:
https://github.com/jcjohnson/neural-style/wiki/Techniques-For-Increasing-Image-Quality-Without-Buying-a-Better-GPU

It looks like I will run the standard VGG code and then when that is done, I replace the model path with nin_imagenet.pth? This will allow me to upres images that I make? Or is there something that I am missing?

**Comment by ProGamerGov** [comment]
Yeah, but you'll also have to change the layers as well because NIN uses different layers. "NIN Upres" is also just multiscale generation.
