### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by skanel** [ProGamerGov/neural-style-pt#57]
can you guide me how to pass this error, I am very beginner .

**Comment by ProGamerGov** [comment]
I think that you may have installed PyTorch without GPU support. 

What OS are you using? How did you install PyTorch?

**Comment by ProGamerGov** [comment]
I'm closing this issue for now. If you are still having the same issue, feel free to reopen this issue.
