### ISSUE TITLE
Can't use commands.

### ISSUE THREAD

**Issue by Testin1234** [ProGamerGov/neural-style-pt#58]
C:\Users\USER\Desktop\AI Workspace\DeepDream\neural-style-pt-master>-style_image C:\Users\USER\Desktop\AI Workspace\DeepDream\neural-style-pt-master.golden_gate.jpg
'-style_image' is not recognized as an internal or external command,
operable program or batch file.
Am I using this wrong, or is it broken?

**Comment by ProGamerGov** [comment]
It's not broken. The error message says that you are trying to use `-style_image` as the name of the script. You need to specify the script and optionally the interpreter with: `python neural_style.py -style_image` or `neural_style.py -style_image`.

**Comment by Testin1234** [comment]
Is there a way that I can change the style without it re-generating an image?

**Comment by ProGamerGov** [comment]
@Testin1234 You have to run neural-style-pt again with a different style image, if you want to change the style image.
