### ISSUE TITLE
Is pytorch actually required?

### ISSUE THREAD

**Issue by jcklpe** [ProGamerGov/neural-style-pt#75]
I see that pytorch is listed as a dep, but when I created [this Google Collaboratory notebook](https://colab.research.google.com/drive/1YEeWvuCreoIAFnhGRYQTXtF2Tlj0UCiR?usp=sharing), I can run the neural network just fine without actually installing the pytorch. Is there something I'm missing? Perhaps the neural-style-pt install file takes care of that?

**Comment by ProGamerGov** [comment]
@jcklpe Google Colab has PyTorch (Torch and Torchvision) already preinstalled. You can verify this by running the following code in a cell:

```
import torch
print(torch.__version__)
```

**Comment by jcklpe** [comment]
@ProGamerGov  awesome, thanks!
