### ISSUE TITLE
Using without CUDA?

### ISSUE THREAD

**Issue by bestguy** [ProGamerGov/neural-style-pt#78]
It's been a while but used to be able to run https://github.com/jcjohnson/neural-style without CUDA support (Macbook Pro)

Is this project able to do same?
I see `AssertionError: Torch not compiled with CUDA enabled` after successful install and unsure if required or how to disable.

**Comment by ProGamerGov** [comment]
@bestguy Have you tried using `-gpu c` yet? By default neural-style-pt tries to use your first GPU with `-gpu 0`.

**Comment by bestguy** [comment]
Ah thanks!  Totally forgot, I appreciate the help and this library.  Much easier than the original neural-style!
