### ISSUE TITLE
Print seed used?

### ISSUE THREAD

**Issue by Feez** [ProGamerGov/neural-style-pt#86]
Could it be added to print the seed used? Useful for when want to reproduce the result of a random seed after-the-fact

I believe it is as simple as
```python
print(f"Seed used: {torch.seed()}")
```
But I not familiar enough with Torch or ML libraries in general to know if this is the correct seed and/or if there are side effects to this.

**Comment by ProGamerGov** [comment]
@Feez I tried doing that a while back and it didn't seem to work. Though maybe things have changed since then?

It may be easier to use something like randint: https://docs.python.org/3/library/random.html#functions-for-integers

```
import random
min, max = 0, 9999999
seed = random.randint(min, max)
print(seed)
params.seed = seed
```
