### ISSUE TITLE
No images found after running script

### ISSUE THREAD

**Issue by Mshriver2** [ProGamerGov/neural-style-pt#88]
The script was working fine for me for months. When I tried to generate some new images it ran as it usually does and went through all the iterations. But the output files are nowhere to be found. I even tried giving a full path in -output. Any ideas??

my script"

python neural_style.py -style_image /mnt/e/GFX\ Textures/Patterns/Photoshop\ Pattern\ Pictures/4.jpg -content_image /media/max/90E83424E8340ACC/Users/Ben\ Stiller/Documents/Photoshop\ Projects/penguins/penguin-29.png -output_image /home/max/Documents/github_downloads/neural-style-pt/penguin-45.png -model_file models/nin_imagenet.pth -gpu 0 -backend cudnn -num_iterations 1000 -seed 123 -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 500 -image_size 600 -optimizer adam

"

**Comment by ProGamerGov** [comment]
@Mshriver2 What version of PyTorch are you using?

**Comment by Mshriver2** [comment]
Hey I actually solved that issue I think it is a Dolphin File explorer bug. But another problem I am having is sometimes it just outputs me grey images with no conten
![penguin-47-1-art_100](https://user-images.githubusercontent.com/3216992/136015516-93c0359c-e71f-4024-bfc4-2690fbd0fc0e.png)
t.

**Comment by Mshriver2** [comment]
For the last 48 hours just getting these grey image outputs. I have tried rebooting a few times as well as using diff source and style images.

**Comment by ProGamerGov** [comment]
@Mshriver2 Generally when this happened to me, I changed the image size by a single pixel to get it working again. But your issue may be related to a bug in PyTorch or CUDA?

**Comment by Mshriver2** [comment]
Yeah it does seem to be some sort of cuda/torch bug. As I ran it with just the most basic version of the script than went back to my script and it works again now.

**Comment by ProGamerGov** [comment]
@Mshriver2 Glad to here that it's working again!

**Comment by Mshriver2** [comment]
pretty much solved, thanks @ProGamerGov
