### ISSUE TITLE
Missing final A7 reference

### ISSUE THREAD

**Issue by Vigilence** [ProGamerGov/neural-style-pt#89]
Love the script and it runs smoothly.  However I received an error which pointed to a file not being available. I did some digging and unless I'm mistaken, the last line of code should be pointing to A7.png instead of .png.

`!python neural-style-pt/neural_style.py -style_image '/content/gdrive/MyDrive/NSPT/style/style1' -style_weight 1500 -style_scale 0.5 -content_image '/content/gdrive/MyDrive/NSPT/input/input.jpg' -content_weight 0 -init image -init_image '/content/gdrive/MyDrive/NSPT/output/.png' -learning_rate 1 -print_iter 50 -save_iter 0 -image_size 7200 -num_iterations 10 -model_file '/content/gdrive/MyDrive/NSPT/checkpoints/nin_imagenet.pth' -content_layers relu0,relu1 -style_layers relu0,relu1 -optimizer adam -output_image '/content/gdrive/MyDrive/NSPT/output/A8-FINAL.png' -tv_weight 0 -original_colors 0 -backend cudnn`

from `'/content/gdrive/MyDrive/NSPT/output/.png'`

to `'/content/gdrive/MyDrive/NSPT/output/A7.png'`

**Comment by ProGamerGov** [comment]
@Vigilence I think that you are experiencing the issue with another script, notebook, or project that uses neural-style-pt. There's no Google Drive related paths in this project.

**Comment by Vigilence** [comment]
@ProGamerGov Yes, your absolutely right!
